name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: nolibc
        run: |
          git clone --depth 1 --filter=blob:none --sparse \
            https://github.com/torvalds/linux.git linux
          git -C linux sparse-checkout set tools/include/nolibc

      - run: make NOLIBCDIR=$PWD/linux/tools/include/nolibc
